---


- hosts: analytics
  gather_facts: no
  roles:
      - ffmpeg
      - common
      - redis
      - supervisor
      - mongodb
      - nginx
      - harviewer
      - analytics
      - loadreport
