---


- name: Add ppa:rwky/redis
  apt_repository: >
    repo='deb http://ppa.launchpad.net/rwky/redis/ubuntu precise main'
    state=present
  sudo: True


- name: Install the latest version of redis server
  apt: pkg=redis-server force=yes state=latest
  sudo: True


- name: Make sure that the default redis server is stopped & disabled
  service: name=redis-server state=stopped enabled=no
  sudo: True
