---


- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev
    - libreadline-dev
    - libncurses5-dev
    - libssl-dev
    - perl
    - make
  sudo: True


- name: Upload source nginx
  copy: src=nginx-1.2.8.tar.gz
        dest=/home/{{ server.user }}/nginx-1.2.8.tar.gz
  register: nginx
  tags:
    - nginx


- name: Extract nginx source code
  command: chdir=/home/{{ server.user }}/
           tar zxvf nginx-1.2.8.tar.gz
  when: nginx.changed
  tags:
    - nginx


- name: Upload source nginx-push-stream-module
  copy: src=nginx-push-stream-module.tar.gz
        dest=/home/{{ server.user }}/nginx-push-stream-module.tar.gz
  register: nginx
  tags:
    - nginx


- name: Extract nginx-push-stream-module source code
  command: chdir=/home/{{ server.user }}/
           tar zxvf nginx-push-stream-module.tar.gz
  when: nginx.changed
  tags:
    - nginx


- name: Make sure nginx directories exist
  file: path={{ item }} state=directory owner={{ server.user }}
  with_items:
    - /etc/nginx
    - /var/log/nginx/
  sudo: True
  tags:
    - nginx


- name: Update mime.types
  copy: src=mime.types dest=/etc/nginx/mime.types
  sudo: True
  tags:
    - nginx


- name: Install nginx
  shell: chdir=/home/{{ server.user }}/nginx-1.2.8/
           ./configure --add-module=../nginx-push-stream-module
           && make
           && make install
  when: >
    nginx.changed
  sudo: True
  tags:
    - nginx
