---


- name: Upload source nginx
  copy: src=nginx-1.2.8.tar.gz
        dest=/home/{{ server.user }}/nginx-1.2.8.tar.gz
  register: nginx
  tags:
    - nginx


- name: Extract nginx source code
  command: chdir=/home/{{ server.user }}/
           tar zxvf nginx-1.2.8.tar.gz
  when: nginx.changed
  tags:
    - nginx


- name: Install nginx
  shell: chdir=/home/{{ server.user }}/nginx-1.2.8/
           ./configure
           && make
           && make install
  when: >
    nginx.changed
  sudo: True
  tags:
    - nginx

